### ISSUE TITLE
Try to build with Qt5

### ISSUE THREAD

**Issue by vnaydionov** [vnaydionov/yb-orm#2]
It may not be hard to do, but some fixes will be certainly needed

**Comment by alexander8901** [comment]
What wrong?

 ./configure --with-qt-includes=/home/al/dev/qt5/5.4/gcc_64/include --with-qt-libs=-/home/al/dev/qt5/5.4/gcc_64/lib | grep Qt

checking for the Qt C++ libraries... no

??

**Comment by vnaydionov** [comment]
I'm using command line like this in Ubuntu12.04:
../yb-orm/configure --prefix=/home/vaclav/work/yb-orm.inst-qt5 --with-test-db-url=sqlite+qtsql:///home/vaclav/work/test1_db.sqlite --disable-static --with-qt-includes=/usr/include/qt5

If your configure script doesn't find Qt5, please look at config.log for possible reason,
there you may find what went wrong, for example:
%%
configure:15427: checking for the Qt C++ libraries
configure:15461: g++ -o conftest -g -O2 -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtSql    conftest.cpp  -lQtCore -lQtXml -lQtSql >&5
In file included from /usr/include/qt5/QtCore/qnamespace.h:45:0,
                 from /usr/include/qt5/QtCore/qobjectdefs.h:45,
                 from /usr/include/qt5/QtCore/qobject.h:47,
                 from /usr/include/qt5/QtCore/qabstractanimation.h:45,
                 from /usr/include/qt5/QtCore/QtCore:4,
                 from /usr/include/qt5/QtXml/QtXml:4,
                 from conftest.cpp:24:
/usr/include/qt5/QtCore/qglobal.h:1079:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE."
%%

16.02.2015, 18:15, "alexander8901" <notifications@github.com>:
> What wrong?
>
> ./configure --with-qt-includes=/home/al/dev/qt5/5.4/gcc_64/include --with-qt-libs=-/home/al/dev/qt5/5.4/gcc_64/lib | grep Qt
>
> checking for the Qt C++ libraries... no
>
> ??
>
> —
> Reply to this email directly or view it on GitHub.


-- 
Best regards,
Viacheslav Naydenov.

**Comment by alexander8901** [comment]
Здравствуйте!

в логе есть эта ошибка, как можно решить эту проблему?

 error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE."



С уважением,
Поколенко Александр.


Понедельник, 16 февраля 2015, 7:42 -08:00 от Viacheslav Naydenov <notifications@github.com>:

**Comment by vnaydionov** [comment]
Пришли мне в личку полный файл config.log 17.02.2015, 16:11, "alexander8901" <notifications@github.com>:Здравствуйте!  в логе есть эта ошибка, как можно решить эту проблему?   error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE."    С уважением, Поколенко Александр.   Понедельник, 16 февраля 2015, 7:42 -08:00 от Viacheslav Naydenov <notifications@github.com>: >I'm using command line like this in Ubuntu12.04: >../yb-orm/configure --prefix=/home/vaclav/work/yb-orm.inst-qt5 --with-test-db-url=sqlite+qtsql:///home/vaclav/work/test1_db.sqlite --disable-static --with-qt-includes=/usr/include/qt5 > >If your configure script doesn't find Qt5, please look at config.log for possible reason, >there you may find what went wrong, for example: >%% >configure:15427: checking for the Qt C++ libraries >configure:15461: g++ -o conftest -g -O2 -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtSql conftest.cpp -lQtCore -lQtXml -lQtSql >&5 >In file included from /usr/include/qt5/QtCore/qnamespace.h:45:0, >from /usr/include/qt5/QtCore/qobjectdefs.h:45, >from /usr/include/qt5/QtCore/qobject.h:47, >from /usr/include/qt5/QtCore/qabstractanimation.h:45, >from /usr/include/qt5/QtCore/QtCore:4, >from /usr/include/qt5/QtXml/QtXml:4, >from conftest.cpp:24: >/usr/include/qt5/QtCore/qglobal.h:1079:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE." >%% > >16.02.2015, 18:15, "alexander8901" <notifications@github.com>: >> What wrong? >> >> ./configure --with-qt-includes=/home/al/dev/qt5/5.4/gcc_64/include --with-qt-libs=-/home/al/dev/qt5/5.4/gcc_64/lib | grep Qt >> >> checking for the Qt C++ libraries... no >> >> ?? >> >> — >> Reply to this email directly or view it on GitHub. > > >--  >Best regards, >Viacheslav Naydenov. >— >Reply to this email directly or view it on GitHub .  —Reply to this email directly or view it on GitHub.   -- Best regards,Viacheslav Naydenov.

**Comment by alexander8901** [comment]
Вторник, 17 февраля 2015, 5:14 -08:00 от Viacheslav Naydenov <notifications@github.com>:
>Пришли мне в личку полный файл config.log 17.02.2015, 16:11, "alexander8901" <notifications@github.com>:Здравствуйте!  в логе есть эта ошибка, как можно решить эту проблему?   error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE."    С уважением, Поколенко Александр.   Понедельник, 16 февраля 2015, 7:42 -08:00 от Viacheslav Naydenov <notifications@github.com>: >I'm using command line like this in Ubuntu12.04: >../yb-orm/configure --prefix=/home/vaclav/work/yb-orm.inst-qt5 --with-test-db-url=sqlite+qtsql:///home/vaclav/work/test1_db.sqlite --disable-static --with-qt-includes=/usr/include/qt5 > >If your configure script doesn't find Qt5, please look at config.log for possible reason, >there you may find what went wrong, for example: >%% >configure:15427: checking for the Qt C++ libraries >configure:15461: g++ -o conftest -g -O2 -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtSql conftest.cpp -lQtCore -lQtXml -lQtSql >&5 >In file included from /usr/include/qt5/QtCore/qnamespace.h:45:0, >from /usr/include/qt5/QtCore/qobjectdefs.h:45, >from /usr/include/qt5/QtCore/qobject.h:47, >from /usr/include/qt5/QtCore/qabstractanimation.h:45, >from /usr/include/qt5/QtCore/QtCore:4, >from /usr/include/qt5/QtXml/QtXml:4, >from conftest.cpp:24: >/usr/include/qt5/QtCore/qglobal.h:1079:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE." >%% > >16.02.2015, 18:15, "alexander8901" <notifications@github.com>: >> What wrong? >> >> ./configure --with-qt-includes=/home/al/dev/qt5/5.4/gcc_64/include --with-qt-libs=-/home/al/dev/qt5/5.4/gcc_64/lib | grep Qt >> >> checking for the Qt C++ libraries... no >> >> ?? >> >> — >> Reply to this email directly or view it on GitHub. > > >--  >Best regards, >Viacheslav Naydenov. >— >Reply to this email directly or view it on GitHub .  —Reply to this email directly or view it on GitHub.   -- Best regards,Viacheslav Naydenov. 
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Поколенко Александр.

**Comment by vnaydionov** [comment]
I've managed to check building against the official distribution downloaded from here:
http://www.qt.io/download-open-source/
```./configure``` script works ok if you set up path to the libraries of the distro beforehand:

    export LD_LIBRARY_PATH=/home/user/Qt5/5.4/gcc/lib

Still have to check for how CMake works and on Windows

**Comment by alexander8901** [comment]
Столкнулся с проблемой

    typedef boost::tuple<User,Group> Pair;
    Yb::DomainResultSet<Pair> pair = Yb::query<Pair>(*session)
            .filter_by(Group::c.id==groupId).all();


Errors:

/home/al/dev/qt5/projects/erp/untitled/orm/orm/domain_object.h:514: error: 'get_table_name' is not a member of 'boost::tuples::tuple<Domain::User, Domain::Group>'
         tables.push_back(R::get_table_name());

  /home/al/dev/qt5/projects/erp/untitled/orm/orm/domain_object.h:490: error: no matching function for call to 'boost::tuples::tuple<Domain::User, Domain::Group>::tuple(__gnu_cxx::__alloc_traits<std::allocator<Yb::IntrusivePtr<Yb::DataObject> > >::value_type&)'
         row = R((**it_)[0]);
             ^                                          ^


С уважением,
Поколенко Александр.

**Comment by vnaydionov** [comment]
Now it builds OK in Windows too
