### ISSUE TITLE
yb-orm and gcc v5

### ISSUE THREAD

**Issue by WARrior-Alex** [vnaydionov/yb-orm#24]
after upgrading to ubuntu 15.10 I cannot configure build with default settings. After hours of research I found article [Porting to GCC 5](https://gcc.gnu.org/gcc-5/porting_to.html) and see that preprocessor default behaviour was changed. After I used -P flag for preprocessor build was made successfully! So can you update your build scripts to undestand new GCC v5?

**Comment by vnaydionov** [comment]
I've managed to try Ubuntu15.10 x86_64 using vagrant last weekend. The first problem that I've come across while running tests is that GCC 5.2.1 does not do well with direct calling of destructors: for some unknown reason it tries to call `delete` for such pointers!
So I am forced not to use placement constructors/direct destructor calls.

**Comment by WARrior-Alex** [comment]
I meant I need to write `./configure <some other options> CPPFLAGS=-P` to build yb-orm. without this option configure script cannot determine libboost version (and maybe some other issues, don't know)

**Comment by vnaydionov** [comment]
Oh, I see, I've just used CMake for the build, so the problem did not appear. Indeed, if I use Autotools scripts there is a trouble while determining the version of Boost. May be a newer version of boost.m4 can help?
All in all, the gcc5.2.1 seems a bit buggy: several times I've seen red coloured ICE, specifically when running make -jN.

**Comment by vnaydionov** [comment]
Yes, the updated `boost.m4` seems to solve the issue.

**Comment by WARrior-Alex** [comment]
I'll test it today later and tell you, if it all ok now

**Comment by vnaydionov** [comment]
Please, run `sh ./autogen.sh` in the source tree, and after that `./configure` in your build directory.

**Comment by WARrior-Alex** [comment]
Yes, build is ok now
